version: '3.8'


services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./postgres_db:/var/lib/postgresql/data


  airflow-init:
    build: .
    container_name: airflow_init
    entrypoint: airflow db init
    environment: &airflow_env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    depends_on:
      - postgres

    
  webserver:
    build: .
    container_name: airflow_web
    ports:
      - "8088:8080"
    environment: *airflow_env
    command: webserver
    depends_on:
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags

  
  scheduler:
    build: .
    container_name: airflow_scheduler
    environment: *airflow_env
    command: scheduler
    depends_on:
      - webserver
    volumes:
      - ./dags:/opt/airflow/dags


volumes:
  postgres_db: